re-added beautification stuff in top-level Makefile. can still get full output with make VERBOSE=1. also re-added .lib support, we may want it.

diff --git a/asf-3.7.3/avr32/utils/make/Makefile.avr32.in b/asf-3.7.3/avr32/utils/make/Makefile.avr32.in
--- a/asf-3.7.3/avr32/utils/make/Makefile.avr32.in
+++ b/asf-3.7.3/avr32/utils/make/Makefile.avr32.in
@@ -1,18 +1,98 @@
-# Include the config.mk file from the cwd where the user called make.
+# List of available make goals:
+#
+# all                     Default target, builds the project
+# clean                   Clean up the project
+# rebuild                 Rebuild the project
+#
+# isp                     Use BatchISP instead of avr32program when interfacing
+#                         the target device.
+#
+# chiperase               Perform a JTAG chip erase command
+# cpuinfo                 Get CPU information
+# debug                   Open a debug connection with the MCU
+# erase                   Perform a flash erase
+# halt                    Stop CPU execution
+# program                 Program MCU memory from ELF output file
+# reset                   Reset MCU
+# readregs                Read CPU registers
+# run                     Start CPU execution
+# secureflash             Protect chip by setting security bit
+#
+# doc                     Build the documentation
+# cleandoc                Clean up the documentation
+# rebuilddoc              Rebuild the documentation
+#
+#
+# Copyright (c) 2009-2012 Atmel Corporation. All rights reserved.
+#
+# \asf_license_starts
+#
+# \page License
+#
+# Redistribution and use in source and binary forms, with or without
+# modification, are permitted provided that the following conditions are met:
+#
+# 1. Redistributions of source code must retain the above copyright notice,
+#    this list of conditions and the following disclaimer.
+#
+# 2. Redistributions in binary form must reproduce the above copyright notice,
+#    this list of conditions and the following disclaimer in the documentation
+#    and/or other materials provided with the distribution.
+#
+# 3. The name of Atmel may not be used to endorse or promote products derived
+#    from this software without specific prior written permission.
+#
+# 4. This software may only be redistributed and used in connection with an
+#    Atmel microcontroller product.
+#
+# THIS SOFTWARE IS PROVIDED BY ATMEL "AS IS" AND ANY EXPRESS OR IMPLIED
+# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
+# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT ARE
+# EXPRESSLY AND SPECIFICALLY DISCLAIMED. IN NO EVENT SHALL ATMEL BE LIABLE FOR
+# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
+# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
+# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
+# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
+# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
+# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
+# POSSIBILITY OF SUCH DAMAGE.
+#
+# \asf_license_stop
+#
+#
+# Include the config.mk file from the current working path, e.g., where the
+# user called make.
 include config.mk
+
+# Tool to use to generate documentation from the source code
+DOCGEN          ?= doxygen
 
 # Look for source files relative to the top-level source directory
 VPATH           := $(PRJ_PATH)
 
-# Output project name (target name minus suffix) and target type
+# Output target file
 target          := $(TARGET)
+
+# Output project name (target name minus suffix)
 project         := $(basename $(target))
+
+# Output target file (typically ELF or static library)
+ifeq ($(suffix $(target)),.a)
+target_type     := lib
+else
+ifeq ($(suffix $(target)),.elf)
 target_type     := elf
+else
+$(error "Target type $(target_type) is not supported")
+endif
+endif
 
 # aleph always linux
 os_type         := Linux
 os              := Linux
 
+
+# binaries
 CROSS           ?= avr32-
 AR              := $(CROSS)ar
 AS              := $(CROSS)as
@@ -25,20 +105,79 @@ OBJCOPY         := $(CROSS)objcopy
 OBJDUMP         := $(CROSS)objdump
 SIZE            := $(CROSS)size
 
+RM              := rm
+RMDIR           := rmdir -p --ignore-fail-on-non-empty
+
 PROGRAM         := avr32program
 GDBPROXY        := avr32gdbproxy
 BATCHISP        := batchisp
 ispflags-y      := -device at32$(PART) -hardware usb -operation
 
-# Don't use make's built-in rules and variables, entering dir etc.
-MAKEFLAGS       += -rR --no-print-directory
+# Strings for beautifying output
+MSG_CLEAN_FILES         = "RM      *.o *.d"
+MSG_CLEAN_DIRS          = "RMDIR   $(strip $(clean-dirs))"
+MSG_CLEAN_DOC           = "RMDIR   $(docdir)"
+MSG_MKDIR               = "MKDIR   $(dir $@)"
+
+MSG_INFO                = "INFO    "
+
+MSG_ARCHIVING           = "AR      $@"
+MSG_ASSEMBLING          = "AS      $@"
+MSG_BINARY_IMAGE        = "OBJCOPY $@"
+MSG_COMPILING           = "CC      $@"
+MSG_COMPILING_CXX       = "CXX     $@"
+MSG_EXTENDED_LISTING    = "OBJDUMP $@"
+MSG_IHEX_IMAGE          = "OBJCOPY $@"
+MSG_LINKING             = "LN      $@"
+MSG_PREPROCESSING       = "CPP     $@"
+MSG_SIZE                = "SIZE    $@"
+MSG_SYMBOL_TABLE        = "NM      $@"
+
+MSG_GETTING_CPU_INFO    = "JTAG    cpuinfo"
+MSG_HALTING             = "JTAG    halt"
+MSG_ERASING_CHIP        = "JTAG    chiperase"
+MSG_ERASING             = "JTAG    erase"
+MSG_PROGRAMMING         = "JTAG    program $(target)"
+MSG_SECURING_FLASH      = "JTAG    secure flash"
+MSG_RESETTING           = "JTAG    reset"
+MSG_DEBUGGING           = "JTAG    debug"
+MSG_RUNNING             = "JTAG    run"
+MSG_READING_CPU_REGS    = "JTAG    readregs"
+
+MSG_GENERATING_DOC      = "DOXYGEN $(docdir)"
+
+# Don't use make's built-in rules and variables
+MAKEFLAGS       += -rR
+
+# Don't print 'Entering directory ...'
+MAKEFLAGS       += --no-print-directory
 
 # Function for reversing the order of a list
 reverse = $(if $(1),$(call reverse,$(wordlist 2,$(words $(1)),$(1)))) $(firstword $(1))
 
+# Hide command output by default, but allow the user to override this
+# by adding V=1 on the command line.
+#
+# This is inspired by the Kbuild system used by the Linux kernel.
+ifdef V
+  ifeq ("$(origin V)", "command line")
+    VERBOSE = $(V)
+  endif
+endif
+ifndef VERBOSE
+  VERBOSE = 0
+endif
+
+ifeq ($(VERBOSE), 1)
+  Q =
+else
+  Q = @
+endif
+
 arflags-gnu-y           := $(ARFLAGS)
 asflags-gnu-y           := $(ASFLAGS)
 cflags-gnu-y            := $(CFLAGS)
+cxxflags-gnu-y          := $(CXXFLAGS)
 cppflags-gnu-y          := $(CPPFLAGS)
 cpuflags-gnu-y          :=
 dbgflags-gnu-y          := $(DBGFLAGS)
@@ -46,6 +185,7 @@ libflags-gnu-y          := $(foreach LIB,$(LIBS),-l$(LIB))
 ldflags-gnu-y           := $(LDFLAGS)
 clean-files             :=
 clean-dirs              :=
+
 clean-files             += $(wildcard $(target) $(project).map)
 clean-files             += $(wildcard $(project).hex $(project).bin)
 clean-files             += $(wildcard $(project).lss $(project).sym)
@@ -56,21 +196,27 @@ cflags-gnu-y    += -pipe
 asflags-gnu-y   += -pipe
 ldflags-gnu-y   += -pipe
 
-arflags-gnu-y   += rcs # Archiver flags.
+# Archiver flags.
+arflags-gnu-y   += rcs
 
-# Always enable warnings. And be very careful about implicit declarations.
+# Always enable warnings. And be very careful about implicit
+# declarations.
 cflags-gnu-y    += -Wall -Wstrict-prototypes -Wmissing-prototypes
 cflags-gnu-y    += -Werror-implicit-function-declaration
-
+cxxflags-gnu-y  += -Wall
 # IAR doesn't allow arithmetic on void pointers, so warn about that.
 cflags-gnu-y    += -Wpointer-arith
+cxxflags-gnu-y  += -Wpointer-arith
 
 # Preprocessor flags.
 cppflags-gnu-y  += $(foreach INC,$(addprefix $(PRJ_PATH)/,$(INC_PATH)),-I$(INC))
 asflags-gnu-y   += $(foreach INC,$(addprefix $(PRJ_PATH)/,$(INC_PATH)),'-Wa,-I$(INC)')
-cpuflags-gnu-y  += -march=$(ARCH) -mpart=$(PART) # CPU specific flags.
 
-depflags        = -MD -MP -MQ $@ # Dependency file flags.
+# CPU specific flags.
+cpuflags-gnu-y  += -march=$(ARCH) -mpart=$(PART)
+
+# Dependency file flags.
+depflags        = -MD -MP -MQ $@
 
 # Debug specific flags.
 ifdef BUILD_DEBUG_LEVEL
@@ -88,25 +234,33 @@ endif
 
 # Relax compilation and linking.
 cflags-gnu-y    += -mrelax
+cxxflags-gnu-y  += -mrelax
 asflags-gnu-y   += -mrelax
 ldflags-gnu-y   += -Wl,--relax,--direct-data
 
-cflags-gnu-y    += -mno-cond-exec-before-reload # Patch for compiler bug
+# Patch for compiler bug
+cflags-gnu-y    += -mno-cond-exec-before-reload 
+cxxflags-gnu-y  += -mno-cond-exec-before-reload
 
 # Always preprocess assembler files.
 asflags-gnu-y   += -x assembler-with-cpp
 # Compile C files using the GNU99 standard.
 cflags-gnu-y    += -std=gnu99
+# Compile C++ files using the GNU++98 standard.
+cxxflags-gnu-y  += -std=gnu++98
 
 # Use signed character type when compiling.
 cflags-gnu-y    += -funsigned-char
+cxxflags-gnu-y  += -funsigned-char
 
 # Don't use strict aliasing (very common in embedded applications).
 cflags-gnu-y    += -fno-strict-aliasing
+cxxflags-gnu-y  += -fno-strict-aliasing
 
 # Separate each function and data into its own separate section to allow
 # garbage collection of unused sections.
 cflags-gnu-y    += -ffunction-sections -fdata-sections
+cxxflags-gnu-y  += -ffunction-sections -fdata-sections
 
 # Garbage collect unreferred sections when linking.
 ldflags-gnu-y   += -Wl,--gc-sections
@@ -124,10 +278,11 @@ ldflags-gnu-y   += $(foreach _LIB_PATH,$(addprefix $(PRJ_PATH)/,$(LIB_PATH)),-L$
 
 a_flags  = $(cpuflags-gnu-y) $(depflags) $(cppflags-gnu-y) $(asflags-gnu-y) -D__ASSEMBLY__
 c_flags  = $(cpuflags-gnu-y) $(dbgflags-gnu-y) $(depflags) $(optflags-gnu-y) $(cppflags-gnu-y) $(cflags-gnu-y)
+cxx_flags= $(cpuflags-gnu-y) $(dbgflags-gnu-y) $(depflags) $(optflags-gnu-y) $(cppflags-gnu-y) $(cxxflags-gnu-y)
 l_flags  = $(cpuflags-gnu-y) $(optflags-gnu-y) $(ldflags-gnu-y)
 ar_flags = $(arflags-gnu-y)
 
-# Source files list and part information must already be included before
+# Source files list and part informations must already be included before
 # running this makefile
 
 # If a custom build directory is specified, use it -- force trailing / in directory name.
@@ -141,29 +296,38 @@ endif
 obj-y                   := $(addprefix $(build-dir), $(addsuffix .o,$(basename $(CSRCS) $(ASSRCS))))
 # Create dependency files list from source files list.
 dep-files               := $(wildcard $(foreach f,$(obj-y),$(basename $(f)).d))
+
 clean-files             += $(wildcard $(obj-y))
 clean-files             += $(dep-files)
+
 clean-dirs              += $(call reverse,$(sort $(wildcard $(dir $(obj-y)))))
 
 # Default target.
 .PHONY: all
+ifeq ($(target_type),lib)
+all: $(target) $(project).lss $(project).sym
+else
+ifeq ($(target_type),elf)
 all: $(target) $(project).lss $(project).sym $(project).hex $(project).bin
+endif
+endif
 
 # Clean up the project.
 .PHONY: clean
 clean:
-	@$(if $(strip $(clean-files)),echo "RM      *.o *.d")
-	$(if $(strip $(clean-files)),rm $(clean-files),)
-	@$(if $(strip $(clean-dirs)),echo "RMDIR   $(strip $(clean-dirs))")
+	@$(if $(strip $(clean-files)),echo $(MSG_CLEAN_FILES))
+	$(if $(strip $(clean-files)),$(Q)$(RM) $(clean-files),)
+	@$(if $(strip $(clean-dirs)),echo $(MSG_CLEAN_DIRS))
 # Remove created directories, and make sure we only remove existing
 # directories, since recursive rmdir might help us a bit on the way.
-	$(if $(strip $(clean-dirs)),                        \
+	$(Q)$(if $(strip $(clean-dirs)),                        \
 		for directory in $(strip $(clean-dirs)); do     \
 			if [ -d "$$directory" ]; then           \
-				rmdir -p --ignore-fail-on-non-empty $$directory;           \
+				$(RMDIR) $$directory;           \
 			fi                                      \
 		done                                            \
 	)
+
 
 # Rebuild the project.
 .PHONY: rebuild
@@ -174,45 +338,79 @@ objfiles: $(obj-y)
 
 # Create object files from C source files.
 $(build-dir)%.o: %.c $(MAKEFILE_PATH) config.mk
-	test -d $(dir $@) || echo "MKDIR   $(dir $@)"
-	test -d $(dir $@) || mkdir -p $(dir $@)
-	$(CC) $(c_flags) -c $< -o $@
+	$(Q)test -d $(dir $@) || echo $(MSG_MKDIR)
+	$(Q)test -d $(dir $@) || mkdir -p $(dir $@)
+	@echo $(MSG_COMPILING)
+	$(Q)$(CC) $(c_flags) -c $< -o $@
+
+# Create object files from C++ source files.
+$(build-dir)%.o: %.cpp $(MAKEFILE_PATH) config.mk
+	$(Q)test -d $(dir $@) || echo $(MSG_MKDIR)
+	$(Q)test -d $(dir $@) || mkdir -p $(dir $@)
+	@echo $(MSG_COMPILING_CXX)
+	$(Q)$(CXX) $(cxx_flags) -c $< -o $@
 
 # Preprocess and assemble: create object files from assembler source files.
 $(build-dir)%.o: %.s $(MAKEFILE_PATH) config.mk
-	test -d $(dir $@) || echo "MKDIR   $(dir $@)"
-	test -d $(dir $@) || mkdir -p $(dir $@)
-	$(CC) $(a_flags) -c $< -o $@
+	$(Q)test -d $(dir $@) || echo $(MSG_MKDIR)
+	$(Q)test -d $(dir $@) || mkdir -p $(dir $@)
+	@echo $(MSG_ASSEMBLING)
+	$(Q)$(CC) $(a_flags) -c $< -o $@
 
 # Preprocess and assemble: create object files from assembler source files.
 $(build-dir)%.o: %.S $(MAKEFILE_PATH) config.mk
-	test -d $(dir $@) || echo "MKDIR   $(dir $@)"
-	test -d $(dir $@) || mkdir -p $(dir $@)
-	$(CC) $(a_flags) -c $< -o $@
+	$(Q)test -d $(dir $@) || echo $(MSG_MKDIR)
+	$(Q)test -d $(dir $@) || mkdir -p $(dir $@)
+	@echo $(MSG_ASSEMBLING)
+	$(Q)$(CC) $(a_flags) -c $< -o $@
 
 # Include all dependency files to add depedency to all header files in use.
 include $(dep-files)
 
+ifeq ($(target_type),lib)
+# Archive object files into an archive
+$(target): $(MAKEFILE_PATH) config.mk $(obj-y)
+	@echo $(MSG_ARCHIVING)
+	$(Q)$(AR) $(ar_flags) $@ $(obj-y)
+	@echo $(MSG_SIZE)
+	$(Q)$(SIZE) -Bxt $@
+else
+ifeq ($(target_type),elf)
 # Link the object files into an ELF file. Also make sure the target is rebuilt
 # if the common Makefile.in or project config.mk is changed.
 $(target): $(PRJ_PATH)/$(LINKER_SCRIPT) $(MAKEFILE_PATH) config.mk $(obj-y)
-	@echo "LN      $@"
-	$(LD) $(l_flags) $(obj-y) -Wl,--start-group $(libflags-gnu-y) -Wl,--end-group -o $@ -lm
-	$(SIZE) -Ax $@
-	$(SIZE) -Bx $@
+	@echo $(MSG_LINKING)
+	$(Q)$(LD) $(l_flags) $(obj-y) -Wl,--start-group $(libflags-gnu-y) -Wl,--end-group -o $@ -lm
+	@echo $(MSG_SIZE)
+	$(Q)$(SIZE) -Ax $@
+	$(Q)$(SIZE) -Bx $@
+endif
+endif
 
 # Create extended function listing from target output file.
 %.lss: $(target)
-	$(OBJDUMP) -h -S $< > $@
+	@echo $(MSG_EXTENDED_LISTING)
+	$(Q)$(OBJDUMP) -h -S $< > $@
 
 # Create symbol table from target output file.
 %.sym: $(target)
-	$(NM) -n $< > $@
+	@echo $(MSG_SYMBOL_TABLE)
+	$(Q)$(NM) -n $< > $@
 
 # Create Intel HEX image from ELF output file.
 %.hex: $(target)
-	$(OBJCOPY) -O ihex $< $@
+	@echo $(MSG_IHEX_IMAGE)
+	$(Q)$(OBJCOPY) -O ihex $< $@
 
 # Create binary image from ELF output file.
 %.bin: $(target)
-	$(OBJCOPY) -O binary $< $@
+	@echo $(MSG_BINARY_IMAGE)
+	$(Q)$(OBJCOPY) -O binary $< $@
+
+# Use separate target rules depending on USB (BatchISP) or JTAG (avr32program)
+# interface to the target device.
+ifeq ($(findstring isp,$(MAKECMDGOALS)),)
+include $(addprefix $(dir $(MAKEFILE_PATH)), Makefile.avr32program.in)
+else
+include $(addprefix $(dir $(MAKEFILE_PATH)), Makefile.batchisp.in)
+endif
